"use strict";
/* Lazy 3D board viewer. The three.js bundle is inert compressed text until this view opens. */
window.Review3D = (() => {
  const style = document.createElement("style"); style.textContent = `.mode-3d{background:var(--line)}.mode-3d .view3d{background:var(--paper);min-width:0;position:relative}.mode-3d .view3d.one{grid-column:1/-1}.mode-3d canvas{display:block;width:100%;height:100%}.mode-3d .marker3d{position:absolute;z-index:2;pointer-events:none;transform:translate(-50%,-100%);font:700 13px system-ui,sans-serif;line-height:1;white-space:nowrap;color:var(--ink);text-shadow:0 1px 2px var(--paper),1px 0 2px var(--paper),-1px 0 2px var(--paper),0 -1px 2px var(--paper)}.loading,.empty3d{position:absolute;inset:0;display:grid;place-items:center;color:var(--muted);margin:0}#modes button[aria-disabled=true]{cursor:not-allowed;opacity:.55}`; document.head.appendChild(style);
  let active = null, bundle;
  const decode = async id => new Response(new Blob([Uint8Array.from(atob(window.REVIEW_DATA.blobs[id]), c => c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer();
  const loadThree = async () => {
    if (window.THREE3D) return window.THREE3D;
    if (!bundle) bundle = (async () => { const text = document.querySelector("#three-bundle").textContent.trim(), bytes = Uint8Array.from(atob(text), c => c.charCodeAt(0)); const code = await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"))).text(); const script = document.createElement("script"); script.textContent = code; document.head.appendChild(script); return window.THREE3D; })();
    return bundle;
  };
  const bg = () => getComputedStyle(document.documentElement).getPropertyValue(matchMedia("(prefers-color-scheme: dark)").matches ? "--bg" : "--paper").trim() || "#f5f4ef";
  const tint = action => new window.THREE3D.THREE.Color(getComputedStyle(document.documentElement).getPropertyValue(`--${action}`).trim() || ({ added:"#198c39", removed:"#c52b3b", modified:"#bd7200" })[action]);
  const materials = o => { const m = o.material; return Array.isArray(m) ? m : [m]; };
  const disposeObject = root => root?.traverse(o => { if (o.geometry) o.geometry.dispose(); materials(o).filter(Boolean).forEach(x => x.dispose()); });
  function dispose() { if (!active) return; active.dead = true; active.abort?.abort(); active.views.forEach(v => { v.controls?.dispose(); v.renderer?.dispose(); v.canvas?.remove(); }); active.sources.forEach(disposeObject); window.Review3D.state = { disposed:true, disposeCount:(window.Review3D.state?.disposeCount || 0) + 1 }; active = null; }
  function cameraBar() { const bar = document.querySelector("#zoombar"); if (!bar) return; bar.innerHTML = `<span class="muted">Camera</span>${["Top","Bottom","Front","Back","Left","Right","3D","Reset"].map(n => `<button data-3d-camera="${n.toLowerCase()}">${n}</button>`).join("")}`; bar.querySelectorAll("[data-3d-camera]").forEach(b => b.onclick = () => frame(b.dataset["3dCamera"])); }
  function frame(direction = "3d") { if (!active?.box) return; const { THREE } = window.THREE3D, b = active.box, c = b.getCenter(new THREE.Vector3()), dirs = { top:[0,1,0], bottom:[0,-1,0], front:[0,0,-1], back:[0,0,1], left:[-1,0,0], right:[1,0,0], "3d":[1,.99,-1], reset:[1,.99,-1] }, d = new THREE.Vector3(...dirs[direction]).normalize(), radius = b.getBoundingSphere(new THREE.Sphere()).radius;
    active.views.forEach(v => { const vfov = THREE.MathUtils.degToRad(v.camera.fov), hfov = 2 * Math.atan(Math.tan(vfov / 2) * v.camera.aspect), distance = radius / Math.sin(Math.min(vfov, hfov) / 2) * 1.08; v.camera.up.set(...((direction === "top" || direction === "bottom") ? [0,0,-1] : [0,1,0])); v.controls._quat.setFromUnitVectors(v.camera.up, new THREE.Vector3(0,1,0)); v.controls._quatInverse.copy(v.controls._quat).invert(); v.camera.position.copy(c).addScaledVector(d, distance); v.controls.target.copy(c); v.camera.near = distance / 100; v.camera.far = distance * 100; v.camera.updateProjectionMatrix(); v.controls.update(); }); render(); }
  function render() { active?.views.forEach(v => { v.renderer.render(v.scene, v.camera); v.labels?.forEach(m => { const p = m.position.clone().project(v.camera), w = v.canvas.clientWidth, h = v.canvas.clientHeight; m.el.style.display = p.z > 1 ? "none" : "block"; m.el.style.left = `${(p.x * .5 + .5) * w}px`; m.el.style.top = `${(-p.y * .5 + .5) * h}px`; }); }); }
  function resize() { if (!active) return; active.views.forEach(v => { const r = v.host.getBoundingClientRect(); v.renderer.setSize(r.width, r.height, false); v.camera.aspect = r.width / Math.max(r.height, 1); v.camera.updateProjectionMatrix(); }); render(); }
  const component = (root, ref) => { let found; root.traverse(o => { if (!found && o.name === ref) found = o; }); return found; };
  function cloneMaterials(root, change, fade = false) { const original = [], changed = []; root?.traverse(o => { if (!o.isMesh) return; const before = materials(o); const after = before.map(m => { const n = m.clone(); if (fade) { n.transparent = true; n.opacity = .25; n.color?.set("#b8b8b8"); } else { const c = tint(change.action); n.color?.lerp(c, .7); if (n.emissive) { n.emissive.copy(c); n.emissiveIntensity = .7; } } return n; }); original.push(...before); changed.push(...after); o.material = Array.isArray(o.material) ? after : after[0]; }); return { original, changed }; }
  function marker(view, node, change) { const { THREE } = window.THREE3D, b = new THREE.Box3().setFromObject(node), position = b.getCenter(new THREE.Vector3()), el = document.createElement("span"); position.y = b.max.y + .004; el.className = `marker3d ${change.action}`; el.dataset.ref = change.ref; el.textContent = `${change.action === "added" ? "＋" : change.action === "removed" ? "−" : "≡"} ${change.ref || ""}`; el.style.color = `#${tint(change.action).getHexString()}`; view.host.appendChild(el); const m = { position, el }; (view.labels ||= []).push(m); return m; }
  function ghost(scene, node, change) { const { THREE } = window.THREE3D, g = node.clone(true), red = tint("removed"); g.name = `ghost:${change.ref}`; g.traverse(o => { if (!o.isMesh) return; o.material = new THREE.MeshBasicMaterial({ color:red, transparent:true, opacity:.45, depthTest:false, depthWrite:false }); const edge = new THREE.LineSegments(new THREE.EdgesGeometry(o.geometry,30), new THREE.LineBasicMaterial({ color:red, depthTest:false, depthWrite:false })); o.add(edge); }); scene.add(g); return g; }
  function outline(scene, root, colour) { const { THREE } = window.THREE3D; let n; root.traverse(o => { if (!n && o.isMesh && /PCB/i.test(o.name)) n = o; }); if (!n) return null; const line = new THREE.LineSegments(new THREE.EdgesGeometry(n.geometry, 30), new THREE.LineBasicMaterial({ color:colour, depthTest:false })); n.updateWorldMatrix(true, false); line.applyMatrix4(n.matrixWorld); scene.add(line); return line; }
  function view(host, roots) { const { THREE, OrbitControls } = window.THREE3D, renderer = new THREE.WebGLRenderer({ antialias:true }); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setClearColor(bg()); const camera = new THREE.PerspectiveCamera(35,1,.01,1000), scene = new THREE.Scene(); scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2)); const light = new THREE.DirectionalLight(0xffffff,3); light.position.set(1,-1,2); scene.add(light, ...roots); host.appendChild(renderer.domElement); const controls = new OrbitControls(camera, renderer.domElement), v = { host, canvas:renderer.domElement, renderer, camera, scene, controls }; controls.enableDamping = true; controls.addEventListener("change", () => { if (active.syncing) return; active.syncing = true; active.views.forEach(q => { if (q !== v) { q.camera.position.copy(camera.position); q.controls.target.copy(controls.target); q.controls.update(); } }); active.syncing = false; render(); }); active.views.push(v); return v; }
  function setBlend(value) { if (!active?.blend) return; active.blend.value = value; active.blend.base.forEach(m => { m.transparent = true; m.opacity = 1 - value; }); active.blend.head.forEach(m => { m.transparent = true; m.opacity = value; }); window.Review3D.state.blend = value; render(); }
  function toggleBlend() { setBlend(active.blend.value < .5 ? 1 : 0); }
  async function show(stage, project, appState) {
    dispose(); const model = project.board.model3d || {}, sides = ["base","head"], mode = appState.m, session = active = { views:[], sources:[], dead:false, start:performance.now(), mode, changes:project.changes.filter(c => c.kind === "footprint") }; window.Review3D.state = { disposed:false, disposeCount:window.Review3D.state?.disposeCount || 0, nodes:[], cameras:[], highlights:[], ghosts:[] }; stage.className = "mode-3d"; stage.innerHTML = `<p class="loading">Loading 3D board…</p>`; cameraBar(); const T = await loadThree(); if (session.dead) return;
    const models = await Promise.all(sides.map(async side => model[side] ? new Promise((resolve,reject) => decode(model[side]).then(buf => new T.GLTFLoader().parse(buf,"",resolve,reject))) : null)); if (session.dead) return; const roots = models.map(g => g?.scene || null); session.sources = roots.filter(Boolean); const box = new T.THREE.Box3(); roots.forEach(r => r && box.union(new T.THREE.Box3().setFromObject(r))); if (box.isEmpty()) { stage.innerHTML = '<p class="empty">No 3D board model was exported.</p>'; return; } session.box = box; window.Review3D.state.box = box; roots.forEach(r => r?.traverse(n => { if (n.name) window.Review3D.state.nodes.push(n.name); }));
    const highlight = (side, v) => session.changes.filter(c => side === "head" ? c.action !== "removed" : c.action !== "added").forEach(c => { const n = component(roots[side === "head" ? 1 : 0], c.ref); if (!n) return; const h = cloneMaterials(n,c); const m = marker(v,n,c); window.Review3D.state.highlights.push({ ref:c.ref, side, original:h.original, materials:h.changed, marker:m }); });
    stage.innerHTML = "";
    if (mode === "side") { roots.forEach((r,i) => { const host = document.createElement("section"); host.className = "vp view3d"; host.innerHTML = `<span class="tag">${i ? "Head" : "Base"}</span>`; stage.appendChild(host); if (r) { const v = view(host,[r]); highlight(i ? "head" : "base",v); } else host.innerHTML += '<p class="empty3d">Board not in this revision</p>'; }); }
    else { const host = document.createElement("section"); host.className = "vp view3d one"; host.innerHTML = `<span class="tag">${mode === "overlay" ? "Base position (red ghost) · Changed now (amber)" : mode === "semantic" ? "Changes only" : "Base ↔ Head"}</span>`; stage.appendChild(host); const head = roots[1], base = roots[0], v = view(host, mode === "blend" ? roots.filter(Boolean) : head ? [head] : base ? [base] : []);
      if (mode === "overlay") { highlight("head",v); session.changes.filter(c => c.action === "removed" || c.action === "modified").forEach(c => { const n = component(base,c.ref); if (n) window.Review3D.state.ghosts.push({ ref:c.ref, object:ghost(v.scene,n,c), translation:n.getWorldPosition(new T.THREE.Vector3()).toArray() }); }); outline(v.scene,base,tint("removed")); outline(v.scene,head,tint("added")); }
      else if (mode === "blend") { const bm=[], hm=[]; base?.traverse(o => { if (o.isMesh) bm.push(...materials(o)); }); head?.traverse(o => { if (o.isMesh) hm.push(...materials(o)); }); session.blend={base:bm,head:hm,value:appState.blend ?? .5}; setBlend(session.blend.value); }
      else if (mode === "semantic") { const refs = new Set(session.changes.filter(c => c.action !== "removed").map(c => c.ref)); window.Review3D.state.faded = []; head?.traverse(n => { if (n.name && !refs.has(n.name) && /^[A-Z]+\d+/.test(n.name)) { const f = cloneMaterials(n,null,true); window.Review3D.state.faded.push({ ref:n.name, materials:f.changed }); } }); highlight("head",v); }
    }
    resize(); frame("3d"); window.Review3D.state.cameras = session.views.map(v => v.camera); window.Review3D.state.controls = session.views.map(v => v.controls); window.Review3D.state.setBlend = setBlend; window.Review3D.state.toggleBlend = toggleBlend; await new Promise(requestAnimationFrame); window.Review3D.state.firstFrameMs = performance.now()-session.start; window.Review3D.state.firstFrame = true; const signal = (session.abort = new AbortController()).signal; window.addEventListener("resize",resize,{signal}); matchMedia("(prefers-color-scheme: dark)").addEventListener("change",() => { session.views.forEach(v => v.renderer.setClearColor(bg())); render(); },{signal});
  }
  return { show, dispose, cameraBar, frame, setBlend, toggleBlend, get state() { return window.__review3dState; }, set state(v) { window.__review3dState = v; } };
})();
